apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/path: "devsecops/data/acme/machine-user"
  name: github-access-secret
  namespace: {{ .Release.Namespace}}
type: Opaque
stringData:
  accessToken: <machine-user-PAT-token>
