apiVersion: v1
kind: Service
metadata:
  name: {{ include "gh-org-checks.fullname" . }}
  labels:
    {{- include "gh-org-checks.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gh-org-checks.selectorLabels" . | nindent 4 }}
